### PR TITLE
Upgrade dependencies and align with cert-manager/webhook-example

### PR DESCRIPTION
**Pull request by splattner**
Based on current state of
- https://github.com/cert-manager/webhook-example
- https://github.com/cert-manager/webhook-example/pull/50

I updated all the dependencies and made the necessary changes for this to build

### CODE REVIEW

**Comment by splattner** [comment]
what does it take to get this merged?

**Comment by arnediekmann** [comment]
I'm sorry, thanks for your amazing work on this. I am testing this now. 

I am currently a bit sow to respond to these because I have so much other stuff to attend to, and I'm not really using the plugin anymore. Maybe we could also transfer the repository to your account if you were willing to support this further.

**Comment by arnediekmann** [comment]
I just release version `0.1.2` that incorporates your changes ... do let me know if that works. And maybe you have an idea on how to change maintenance of this repo so it serves the community better...

**Comment by splattner** [comment]
> I just release version `0.1.2` that incorporates your changes ... do let me know if that works. And maybe you have an idea on how to change maintenance of this repo so it serves the community better...

Awesome, thank you.
We (https://github.com/puzzle/) are interested in maintaining this. I'll get in touch with you, but currently also busy, will be in the next few month if this is ok for you.

**Comment by arnediekmann** [comment]
Hey, of course, just let me know when you are ready for a transfer of the repository 👌😌

**Pull request merged**
